name: "metis-sequencer"

services:
  exporter:
    image: metisdao/sequencer-exporter:v0.0.4
    platform: linux/amd64
    restart: unless-stopped
    stop_grace_period: 30s
    network_mode: host
    command:
      - -config
      - /config.yaml
    volumes:
      - ./config.yaml:/config.yaml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
